### ISSUE TITLE
make install fails when swig is missing

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/qmckl#95]

**Comment by q-posev** [comment]
I see that CI is failing due to this. `make install` should not try to build the Python interface, we have `make python-install` for that. The flow can be due to `dist_python_data` in the `Makefile.am` but I am not sure.

On the same note: I see the following error in the CI:
`python/src/qmckl_include.i:79: Error: Can't apply (int64_t *ARGOUT_ARRAY1,int64_t DIM1) to (int64_t *const walk_num).  Number of arguments don't match.` 
Looks like some of the recent changes breaks the auto-generation of the Python interface. `qmckl_include.i` is auto-generated by the [process_header.py](https://github.com/TREX-CoE/qmckl/blob/master/python/src/process_header.py) script.

**Comment by q-posev** [comment]
Not 100% sure but this commit 499178c3daacf9f5511446d8f849b735a5a0a551 looks weird, it should have disabled only the `print`, not the full `if` clause (there was `continue` inside which advances the loop iterator)

**Comment by scemama** [comment]
You are right. I should have commented only the print, not the whole
block.

**Comment by q-posev** [comment]
I fixed it on master but I still think that `make install` should be decoupled from the Python API compilation

**Comment by q-posev** [comment]
Just confirmed: not packaging Python API will fix this, i.e. renaming `dist_python_DATA` to smth not automake-related.

**Comment by scemama** [comment]
I just made the change to set the default behavior to `--disable-python` to fix the CI.
I think it would be really helpful for users if we can run `make dist` and provide a `tar.gz` file that includes the SWIG-generated files. This way, users can easily run `make python-install` without having to worry about a lot of dependencies. That's why I created the `dist_python_DATA` variable.
